### ISSUE TITLE
Filters drawer - not working properly for boolean or enum values

### ISSUE THREAD

**Issue by rustemkk** [SoftwareBrothers/adminjs#1234]
**Describe the bug**

1) UI bug - placeholder and selected value in dropdown is shifted up:
<img width="407" alt="Screenshot 2022-09-01 at 13 26 34" src="https://user-images.githubusercontent.com/5126284/187903307-8d4dc93c-7a39-4ec0-8140-a608e6beba73.png">
<img width="406" alt="Screenshot 2022-09-01 at 13 26 58" src="https://user-images.githubusercontent.com/5126284/187903317-de632c58-0794-424f-a525-65fd0e4373b1.png">

2) after applying by clicking on "Apply changes" button - list is filtered and you see it in url change, but when you open filters drawer again, it looks like nothing is selected:
![1](https://user-images.githubusercontent.com/5126284/187904455-db09cfb0-052f-42e3-9718-0e6e2eccb6da.gif)

So to remove single filter you have to use "Reset" button to remove all filters or select some value in dropdown and fter that click on x to remove it and then "Apply changes".

**Installed libraries and their versions**
I attached examples above from your [demo website](https://adminjs-demo.herokuapp.com/admin/resources/orders). it shows Admin: 6.1.3 & App: 2.0.0.
Same problem for adminjs@6.1.6 on my project.
If it helps - on adminjs@5.7.3 it works as expected:
![2](https://user-images.githubusercontent.com/5126284/187907619-df0c8f7e-e770-49c7-b850-82b6b3bfba06.gif)

**To Reproduce**
1. Open your [demo website](https://adminjs-demo.herokuapp.com/admin/resources/orders).
2. Try to apply boolean or other dropdown filters.
3. See that applied filters not processed properly on dropdowns in filters drawer.

**Expected behavior**
Applied filters should be visible in filters drawer.

**Screenshots**

**Desktop (please complete the following information if relevant):**
 - OS: macOS
 - Browser: any browser, testyed with:
-  - Chrome Version 104.0.5112.101 (Official Build) (arm64), 
-  - Safari Version 15.6 (17613.3.9.1.5),
-  - Firefox 103.0.2 (64-bit)

**Comment by krzysztofstudniarek** [comment]
@jwasiak is it something you can take a look at? 😉

**Comment by jwasiak** [comment]
fixed

**Comment by rustemkk** [comment]
@jwasiak @krzysztofstudniarek 
Hi, thank you so much, think now its better, at least for multiple options dropdown it works as expected. 

For boolean dropdown still has issues, tested on m,y project with latest admin libraries and tested on your [demo website](https://adminjs-demo.herokuapp.com/admin/resources/orders) (Admin: 6.2.5-demo.1 App: 2.0.0).

Right now if you select value for boolean filter - and click "apply changes" - it closes drawer (but shouldn't) and if you open it again - it always thinks you selected "Yes". Also - resetting single filter by clicking on "x" resets its to "No", but should be empty value.

![2](https://user-images.githubusercontent.com/5126284/193770213-bb80feed-b9a3-4020-af33-731a316e7496.gif)

**Comment by rustemkk** [comment]
@jwasiak @krzysztofstudniarek
Hey guys, the problem still present, should I make new issue or could you please reopen this one?

**Comment by krzysztofstudniarek** [comment]
Reopening this one is fine. @jwasiak will you be able to take a look on this?

**Comment by dziraf** [comment]
Just leaving a note on:
> click "apply changes" - it closes drawer (but shouldn't)
The drawer is closed on purpose, otherwise when you open a direct link with `filters.x` present in the address bar, it will open a drawer instead of simply displaying filtered records.

**Comment by rustemkk** [comment]
@dziraf Oh yeah, you're right about that one, this must be new version behavior, in previous version (v.5) drawer stood open after applying filters :)

**Comment by CezarManea** [comment]
I can also confirm that for boolean values the issue hasn't been fixed. 
Can we reopen this?

**Comment by dziraf** [comment]
@rustemkk this should now also be fixed, let me know if there are still any problems

**Comment by dziraf** [comment]
What do you mean by empty records? @robinl3680

**Comment by robinl3680** [comment]
I have a boolean field, after choosing a value ( true/false ) from the field and apply the filter, list is showing empty even we have records with that particular value

**Comment by dziraf** [comment]
Which ORM/ODM adapter do you use?

**Comment by robinl3680** [comment]
@dziraf Additional information, I am not connecting Database directly, instead I am using REST Api's to fetch and load resources. Please do help!

**Comment by dziraf** [comment]
If you're using REST API, are you sure your REST API processes filters correctly?

**Comment by robinl3680** [comment]
How can I check that ? I am using REST API to load my resource, then filter on the resources should be internal and handled by AdminJs ? because I can see apart from bool field other field are working fine with filter!

**Comment by dziraf** [comment]
If you're saying you're not accessing the database directly and using REST API, then your REST API should handle filters and pagination as data access layer.

**Comment by pemakhov** [comment]
Hi there
I have quite a similar bug.
Filtering with booleans works well, but after resetting the boolean filter things break down.
It continues to send this filter but with a null value.
I use AdminJS with Nest.js and Prisma.
[Screencast from 15.02.23 11:32:03.webm](https://user-images.githubusercontent.com/6075087/218991244-3807b95a-2971-45c9-b502-63203a039677.webm)
![image](https://user-images.githubusercontent.com/6075087/218991663-719439aa-f2a7-4f05-ba7a-d1dcd95b1dcc.png)

**Comment by kylewinkler** [comment]
Experiencing a similar issue here:

Filtering a boolean value returns results for false value regardless of whether or not the user selects true or false as the filter option.

Looking into this now to see if it is happening on our end or not (connecting to a nestjs typeorm backend)
