### ISSUE TITLE
Body Parser error when i click login admin panel

### ISSUE THREAD

**Issue by RizoMan** [SoftwareBrothers/adminjs#752]
When i click login in adminbro view, send me this error:

WrongArgumentError: 
  You probably used old `body-parser` middleware, which is not compatible
  with @admin-bro/express. In order to make it work you will have to
  1. move body-parser invocation after the admin bro setup like this:
  
  const adminBro = new AdminBro()
  const router = new buildRouter(adminBro)
  app.use(adminBro.options.rootPath, router)
  
  // body parser goes after the AdminBro router
  app.use(bodyParser())
  
  2. Upgrade body-parser to the latest version and use it like this:
  app.use(bodyParser.json())
  
    at C:\Users\RizoMan\node\directorio_clone\node_modules\@admin-bro\express\lib\buildAuthenticatedRouter.js:52:18
    at Layer.handle [as handle_request] (C:\Users\RizoMan\node\directorio_clone\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\RizoMan\node\directorio_clone\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\RizoMan\node\directorio_clone\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\RizoMan\node\directorio_clone\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\RizoMan\node\directorio_clone\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\RizoMan\node\directorio_clone\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\RizoMan\node\directorio_clone\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\RizoMan\node\directorio_clone\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\RizoMan\node\directorio_clone\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\RizoMan\node\directorio_clone\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\RizoMan\node\directorio_clone\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\RizoMan\node\directorio_clone\node_modules\express\lib\router\index.js:275:10)
    at C:\Users\RizoMan\node\directorio_clone\node_modules\express\lib\router\index.js:635:15
    at next (C:\Users\RizoMan\node\directorio_clone\node_modules\express\lib\router\index.js:260:14)
    at Function.handle (C:\Users\RizoMan\node\directorio_clone\node_modules\express\lib\router\index.js:174:3)

I do extactly they said but nothing changed.

this is my package.json

{
  "name": "directorio_tuciudad",
  "version": "0.0.1",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "nodemon src/index.js",
    "start": "node --trace-warnings src/index.js"
  },
  "author": "Alejandro Suárez",
  "license": "ISC",
  "dependencies": {
    "@admin-bro/express": "^3.1.0",
    "@admin-bro/mongoose": "^1.1.0",
    "admin-bro": "^3.4.0",
    "bcryptjs": "^2.4.3",
    "body-parser": "^1.19.0",
    "connect-flash": "^0.1.1",
    "cookie-parser": "^1.4.5",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "express-formidable": "^1.2.0",
    "express-handlebars": "^3.1.0",
    "express-session": "^1.17.1",
    "method-override": "^3.0.0",
    "mongoose": "^5.10.9",
    "morgan": "^1.10.0",
    "multer": "^1.4.2",
    "passport": "^0.4.0",
    "passport-local": "^1.0.0",
    "path": "^0.12.7",
    "tslib": "^2.1.0"
  },
  "devDependencies": {
    "nodemon": "^1.19.1"
  }
}

**Comment by dashrat** [comment]
Same here. struggling from whole day and landed here in a hope of solution or workaround

**Comment by dashrat** [comment]
Well I got mine solved by moving 
```
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
```

below 
`app.use(adminBro.options.rootPath, adminrouter)`

In my case I was adding following code earlier but after express version 4.17 it has changed. so the adminBro error message might be still giving old solution hint.
```
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: true }))
```

**Comment by Andrukva** [comment]
Has anyone solved this problem? What is offered does not solve the problem.

**Comment by ehsunshine** [comment]
Same problem here

**Comment by darmane** [comment]
Hi! has someone resolved the error? I'm using typescript and this is my config...

`app.use(adminBro.options.rootPath, adminRoutes)
app.use(express.json());
app.use(express.urlencoded({ extended: false }));`

**Comment by guillaumemeyer** [comment]
The error message is clearly inaccurate and misleading. The only way to make it work as of today is by registering the `express.json()` middleware **AFTER** the ` app.use(adminBro.options.rootPath, adminrouter)` statement.

**Comment by Naozumi520** [comment]
I'm getting the "`InternalServerError: stream is not readable`" error, anyone knows why?

**Comment by swarajkumarsingh** [comment]
> Well I got mine solved by moving
> 
> ```
> app.use(express.json());
> app.use(express.urlencoded({ extended: false }));
> ```
> 
> below `app.use(adminBro.options.rootPath, adminrouter)`
> 
> In my case I was adding following code earlier but after express version 4.17 it has changed. so the adminBro error message might be still giving old solution hint. so Instead of this
> 
> ```
> app.use(bodyParser.json())
> app.use(bodyParser.urlencoded({ extended: true }))
> ```
> 
> Write this
> 
> ```
> app.use(express.json());
> app.use(express.urlencoded({ extended: false }));
> ```

this worked thanks
