### ISSUE TITLE
Body Parser Error After Login Page

### ISSUE THREAD

**Issue by WorkImp** [SoftwareBrothers/adminjs#867]
I get body parser error in after login page

WrongArgumentError: 
  You probably used old `body-parser` middleware, which is not compatible
  with @admin-bro/express. In order to make it work you will have to
  1. move body-parser invocation after the admin bro setup like this:
  
  const adminBro = new AdminBro()
  const router = new buildRouter(adminBro)
  app.use(adminBro.options.rootPath, router)
  
  // body parser goes after the AdminBro router
  app.use(bodyParser())
  
  2. Upgrade body-parser to the latest version and use it like this:
  app.use(bodyParser.json())
  
    at C:\Users\KIIT\Desktop\virtuera\hey\backend\server\node_modules\@admin-bro\express\lib\buildAuthenticatedRouter.js:52:18
    at Layer.handle [as handle_request] (C:\Users\KIIT\Desktop\virtuera\hey\backend\server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\KIIT\Desktop\virtuera\hey\backend\server\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\KIIT\Desktop\virtuera\hey\backend\server\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\KIIT\Desktop\virtuera\hey\backend\server\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\KIIT\Desktop\virtuera\hey\backend\server\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\KIIT\Desktop\virtuera\hey\backend\server\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\KIIT\Desktop\virtuera\hey\backend\server\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\KIIT\Desktop\virtuera\hey\backend\server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\KIIT\Desktop\virtuera\hey\backend\server\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\KIIT\Desktop\virtuera\hey\backend\server\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\KIIT\Desktop\virtuera\hey\backend\server\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\KIIT\Desktop\virtuera\hey\backend\server\node_modules\express\lib\router\index.js:275:10)
    at C:\Users\KIIT\Desktop\virtuera\hey\backend\server\node_modules\express\lib\router\index.js:635:15
    at next (C:\Users\KIIT\Desktop\virtuera\hey\backend\server\node_modules\express\lib\router\index.js:260:14)
    at Function.handle (C:\Users\KIIT\Desktop\virtuera\hey\backend\server\node_modules\express\lib\router\index.js:174:3)

**Comment by WorkImp** [comment]
const AdminBroOptions = require('./routes/adminRoute/adminRoute')

const adminBro = new AdminBro(AdminBroOptions)
app.use(adminBro.options.rootPath, adminRoute)

It worked for me!

**Comment by ArslanKathia** [comment]
Well I got mine solved by moving

```
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
```
below
`app.use(adminBro.options.rootPath, adminrouter)`

**Comment by nathanguigui** [comment]
error still present, not accurate and not up to date since the body-parser module is included in express
moreover I succeed to setup admin js multiple time but I'm still loosing multiple days to fix this issue 
To conclud on this comment i have the error only when using `AdminJSExpress.buildAuthenticatedRouter` and not when using `buildRouter`
