### ISSUE TITLE
JSONB Data Corrupted on Edit

### ISSUE THREAD

**Issue by revnode** [SoftwareBrothers/adminjs#868]
**Describe the bug**

This is for a Postgres database with a JSONB field in a table. If that JSONB field has the following JSON in it `{"test": 1}` and that record is updated, that field will get saved as `{"test": "1"}`, casting the int to a string.

I understand that there is functionality to define the types of the properties within a JSON field, but this is impossible to use when the JSONB field contains arbitrary JSON data.

I tried disabling the JSONB field with `{isVisible: false, isDisabled: true}`, but it still corrupted the data. I don't really need the field to be editable or even viewable, but I don't want the data to be corrupted.

I think an easy solution here would be if `isVisible` is set to `false` or `isDisabled` is set to `true`, the field doesn't get modified. There should be no way for the user to change the value if either of those is set.

**Installed libraries and their versions**

* adminjs@4.0.1
* @admin-bro/koa@1.1.1
* @admin-bro/sequelize@1.2.1

**To Reproduce**
1. Create a JSONB column on a table in Postgres.
2. Set the value of the column on a row to `{"test": 1}`
3. Edit something else in the row.
4. That column in the row is now corrupted with `{"test": "1"}`

**Expected behavior**

For JSON data to not be corrupted, even if types are not specified for a JSON field. It's fine if the field isn't editable, visible, etc. as long as the data is not corrupted.

I'm happy to submit a PR for this fixing the issue.

**Comment by dziraf** [comment]
This should be fixed once we merge https://github.com/SoftwareBrothers/adminjs/pull/944

**Comment by tobika** [comment]
@dziraf I still have the problem that JSONB content changes completly to strings when I do edits, version adminjs 6.2.4
